'use strict';
// 10 cols × 18 rows portrait grid.
// '#'=wall, ' '=empty, '1'-'6'=block, 'B'=barrier,
// 'L'=laser-H, 'T'=teleporter, 'H'=hourglass, 'A'=acid-safe
const LEVELS = [

  // ── World 1: Basics (1–10) ───────────────────────────────────────────────

  { name: 'First Steps', timeLimit: 120, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '# 1    1 #',
    '##########',
  ]},

  { name: 'Two Pairs', timeLimit: 120, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#1 2  2 1#',
    '##########',
  ]},

  { name: 'Drop Zone', timeLimit: 120, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#  1  1  #',
    '#  ####  #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Three Green', timeLimit: 120, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#11    1 #',
    '##########',
  ]},

  { name: 'Color Swap', timeLimit: 120, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#12  2 1 #',
    '##########',
  ]},

  { name: 'Shelf Life', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#  1     #',
    '#  ##    #',
    '#        #',
    '#     1  #',
    '#     ## #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Triple Drop', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '###   1  #',
    '#     #  #',
    '#11      #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Four Colors', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#1234 4321',
    '##########',
  ]},

  { name: 'High Shelf', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '# 1   1  #',
    '# ####### ',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#  2  2  #',
    '#  ####  #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Crowd', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#132 231 #',
    '##########',
  ]},

  // ── World 2: Platforms (11–20) ────────────────────────────────────────────

  { name: 'High Dive', timeLimit: 90, grid: [
    '##########',
    '#1      1#',
    '#  ####  #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Split Level', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#  1     #',
    '####     #',
    '#        #',
    '#     1  #',
    '#     ####',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Staircase', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#1       #',
    '###      #',
    '#  1     #',
    '#  ###   #',
    '#    1   #',
    '#    #####',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'The Bridge', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '# 1    1 #',
    '####  ####',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#  2  2  #',
    '##########',
  ]},

  { name: 'Two Floors', timeLimit: 90, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#  1  1  #',
    '#  ####  #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#  2  2  #',
    '#  ####  #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Tower Fall', timeLimit: 90, grid: [
    '##########',
    '#   1    #',
    '#   #    #',
    '#   2    #',
    '#   #    #',
    '#   1    #',
    '#   #    #',
    '#   2    #',
    '#   ######',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Island Hop', timeLimit: 75, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#  1  2  #',
    '#  ## ## #',
    '#        #',
    '#  2  1  #',
    '#  ## ## #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Cascade', timeLimit: 75, grid: [
    '##########',
    '#        #',
    '#1       #',
    '#####    #',
    '#   2    #',
    '#   #### #',
    '#       1#',
    '# ########',
    '#  2     #',
    '#  #######',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'The Canyon', timeLimit: 75, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#1      1#',
    '#  ####  #',
    '#  1  1  #',
    '#  ## ## #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  { name: 'Cross Drop', timeLimit: 75, grid: [
    '##########',
    '#        #',
    '#        #',
    '#  1   2 #',
    '#  ###   #',
    '#        #',
    '#  2   1 #',
    '#  ###   #',
    '#        #',
    '#        #',
    '#  3   3 #',
    '#  ###   #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '##########',
  ]},

  // ── World 3: Hazards (21–25) ──────────────────────────────────────────────

  { name: 'First Barrier', timeLimit: 75, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#1  B  1 #',
    '##########',
  ]},

  { name: 'Barrier Row', timeLimit: 75, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#1B2  2B1#',
    '##########',
  ]},

  { name: 'Laser Gate', timeLimit: 60, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    'L        #',
    '#        #',
    '#        #',
    '# 1   1  #',
    '##########',
  ]},

  { name: 'Dual Laser', timeLimit: 60, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    'L        #',
    '#        #',
    'L        #',
    '#        #',
    '#        #',
    '#1 2  2 1#',
    '##########',
  ]},

  { name: 'Acid Pool', timeLimit: 60, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#  AAAA  #',
    '# 1    1 #',
    '##########',
  ]},

  // ── World 4: Advanced (26–30) ─────────────────────────────────────────────

  { name: 'Teleport', timeLimit: 60, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#1 T  T 1#',
    '##########',
  ], teleporters: [{r1:16,c1:3,r2:16,c2:6}]},

  { name: 'Flip Gravity', timeLimit: 60, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#   6    #',
    '#   H    #',
    '#   #    #',
    '#1 2  2 1#',
    '##########',
  ]},

  { name: 'Mixed Hazards', timeLimit: 60, grid: [
    '##########',
    '#        #',
    '#        #',
    '#        #',
    '#        #',
    '#  1  2  #',
    '#  ## ## #',
    '#        #',
    '#        #',
    'L        #',
    '#        #',
    '#   B    #',
    '#        #',
    '#        #',
    '#        #',
    '#  AAAA  #',
    '#2 1     #',
    '##########',
  ]},

  { name: 'Grand Prix', timeLimit: 60, grid: [
    '##########',
    '#        #',
    '#1       #',
    '####     #',
    '#   2    #',
    '#   #### #',
    '#       1#',
    '# ########',
    '#  2  3  #',
    '#  ## ## #',
    '#        #',
    'L    B   #',
    '#      3 #',
    '#   ##   #',
    '#        #',
    '#  AAAA  #',
    '#        #',
    '##########',
  ]},

  { name: 'The Final', timeLimit: 90, grid: [
    '##########',
    '#   1   ##',
    '#   #    #',
    '#  2  2  #',
    '#  ## ## #',
    '#        #',
    '#3      3#',
    '####### ##',
    '#        #',
    'L  B     #',
    '#        #',
    '#   H    #',
    '#        #',
    '#        #',
    '#        #',
    '#  AAAA  #',
    '#1       #',
    '##########',
  ]},

];

// ── Endless levels ────────────────────────────────────────────────────────
// Dynamic boards are deterministic: the same level number always produces
// the same board. Each is a symmetry/color transform of a campaign board
// whose solution has been validated. These transforms preserve solvability.
const ENDLESS_BASES = [
  9, 11, 12, 13, 14, 15, 16, 17, 18, 19,
  20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
];
const endlessCache = new Map();

function levelRandom(seed) {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    return state / 4294967296;
  };
}

function getLevel(idx) {
  if (idx < LEVELS.length) return LEVELS[idx];
  if (endlessCache.has(idx)) return endlessCache.get(idx);

  const endlessNo = idx - LEVELS.length + 1;
  const random = levelRandom(0xB10CD00 ^ Math.imul(endlessNo, 2654435761));
  const sourceIdx = ENDLESS_BASES[Math.floor(random() * ENDLESS_BASES.length)];
  const source = LEVELS[sourceIdx];
  const hasHorizontalLaser = source.grid.some(row => row.includes('L'));
  const mirror = !hasHorizontalLaser && random() < 0.5;

  const colors = [1, 2, 3, 4, 5, 6];
  for (let i = colors.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [colors[i], colors[j]] = [colors[j], colors[i]];
  }

  const transformRow = row => {
    const recolored = row.replace(/[1-6]/g, ch => String(colors[Number(ch) - 1]));
    return mirror ? [...recolored].reverse().join('') : recolored;
  };
  const transformCol = c => mirror ? 9 - c : c;
  const difficultyBand = Math.floor((endlessNo - 1) / 10);

  const level = {
    ...source,
    name: `Endless ${String(endlessNo).padStart(3, '0')} · ${source.name}`,
    timeLimit: Math.max(45, source.timeLimit - Math.min(30, difficultyBand * 5)),
    grid: source.grid.map(transformRow),
  };

  if (source.teleporters) {
    level.teleporters = source.teleporters.map(t => ({
      ...t,
      c1: transformCol(t.c1),
      c2: transformCol(t.c2),
    }));
  }
  if (source.elevators) {
    level.elevators = source.elevators.map(e => ({ ...e, col: transformCol(e.col) }));
  }

  endlessCache.set(idx, level);
  return level;
}
